apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ticket-app
  template:
    metadata:
      labels:
        app: ticket-app
    spec:
      containers:
      - name: ticket-app
        image: ticket-app:1.0
        ports:
        - containerPort: 80
